version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: employees-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_DATABASE: "dropwizard-employees"
      MYSQL_ROOT_HOST: "%"
    restart: always
#    volumes:
#      - mysql_data:/var/lib/mysql
    ports:
      - 3306
    expose:
      - 3306
#    volumes:
#      - mysql_data: /var/lib/mysql:rw


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: employees-phpmyadmin
    ports:
      - 8181:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      PMA_HOST: mysql
      MYSQL_ROOT_HOST: '%'
    depends_on:
      - mysql
    links:
      - mysql

  employee:
    build:
      context: .
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - mysql
    container_name: employees-container
#
#volumes:
#  mysql_data: